version: '3'
services:
  failserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "MAX_LATENCY_MS=50"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    links:
      - failserver
      - pushgateway
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
