global:
  scrape_interval: 20s
  external_labels:
    monitor: 'failserver-monitor'


rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'failserver'
    scrape_interval: 4s
    static_configs:
      - targets: ['failserver1:8080']
  - job_name: 'pushgateway'
    scrape_interval: 4s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - /etc/failserver.yml
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackboxexporter:9115  # Blackbox exporter.
