global:
  scrape_interval: 20s
  external_labels:
    monitor: 'failserver-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'failserver'
    scrape_interval: 4s
    static_configs:
      - targets: ['failserver:8080']
